"""add secondary manager

Revision ID: 0bc4832e421b
Revises: eee4a5f681e9
Create Date: 2026-03-20 11:27:10.823987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bc4832e421b'
down_revision: Union[str, None] = 'eee4a5f681e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('secondary_manager_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['secondary_manager_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'secondary_manager_id')
    # ### end Alembic commands ###